@startuml WatchPartyUseCase

left to right direction
skinparam actorStyle awesome

actor WatchPartyUser
database WatchPartyDB
database TMDB_API

rectangle "Social Media Watch Party" {
    usecase "Login"
    usecase "ForgotPassword"
    usecase "ForgotEmail"
    usecase "StartWatchParty"
    usecase "PauseWatchParty"
    usecase "EndWatchParty"
    usecase "SearchUsers"
    usecase "ViewFriends"
    usecase "SearchFriends"
    usecase "FriendSeriesList"
    usecase "SearchSeries"
    usecase "ViewLikedSeries"
    usecase "SearchLikedSeries"
    usecase "CurrentlyWatching"
    usecase "SeriesWatched"
    usecase "SeriesToWatch"
    usecase "CreateReview"
    usecase "PostComment"
    usecase "PostLike"
    usecase "SharePost"
    usecase "SortContent"
}

WatchPartyUser --> Login
WatchPartyUser --> ForgotPassword
WatchPartyUser --> ForgotEmail
WatchPartyUser --> StartWatchParty
WatchPartyUser --> PauseWatchParty
WatchPartyUser --> EndWatchParty
WatchPartyUser --> SearchUsers
WatchPartyUser --> ViewFriends
WatchPartyUser --> SearchFriends
WatchPartyUser --> FriendSeriesList
WatchPartyUser --> SearchSeries
WatchPartyUser --> ViewLikedSeries
WatchPartyUser --> SearchLikedSeries
WatchPartyUser --> CurrentlyWatching
WatchPartyUser --> SeriesWatched
WatchPartyUser --> SeriesToWatch
WatchPartyUser --> CreateReview
WatchPartyUser --> PostComment
WatchPartyUser --> PostLike
WatchPartyUser --> SharePost
WatchPartyUser --> SortContent

SearchSeries <-- TMDB_API

SearchUsers <-- WatchPartyDB
ViewFriends <-- WatchPartyDB
SearchFriends <-- WatchPartyDB
SearchLikedSeries <-- WatchPartyDB
FriendSeriesList <-- WatchPartyDB
ViewLikedSeries <-- WatchPartyDB
CurrentlyWatching <-- WatchPartyDB
SeriesWatched <-- WatchPartyDB
SeriesToWatch <-- WatchPartyDB

@enduml