@startuml SocialMediaUsecase

left to right direction
skinparam actorStyle awesome

actor WatchPartyUser
actor Visitor
database WatchPartyDB

rectangle "Social Media" {
    usecase "SearchUsers"
    usecase "ViewFriends"
    usecase "SearchFriends"
    usecase "AddFriend"
    usecase "RemoveFriend"
    usecase "CreateReview"
    usecase "RemoveReview"
    usecase "PostComment"
    usecase "RemoveComment"
    usecase "SubmitLike"
    usecase "UnsubmitLike"
    usecase "SharePost"
    usecase "UnsharePost"
}

WatchPartyUser --> SearchUsers
WatchPartyUser --> ViewFriends
WatchPartyUser --> SearchFriends
WatchPartyUser --> AddFriend
WatchPartyUser --> RemoveFriend
WatchPartyUser --> CreateReview
WatchPartyUser --> RemoveReview
WatchPartyUser --> PostComment
WatchPartyUser --> RemoveComment
WatchPartyUser --> SubmitLike
WatchPartyUser --> UnsubmitLike
WatchPartyUser --> SharePost
WatchPartyUser --> UnsharePost

SearchUsers <-- Visitor

SearchUsers <-- WatchPartyDB
ViewFriends <-- WatchPartyDB
SearchFriends <-- WatchPartyDB
AddFriend <-- WatchPartyDB
RemoveFriend <-- WatchPartyDB
CreateReview <-- WatchPartyDB
PostComment <-- WatchPartyDB
SubmitLike <-- WatchPartyDB
SharePost <-- WatchPartyDB
UnsharePost <-- WatchPartyDB

@enduml